- .gitmodules
The cli-breakout changes on Freshli have been reviewed and merged into the main branch. To facilitate this merge, the freshli submodule has been updated to point at the main branch as opposed to the cli-breakout branch.
> Updates Freshli Submodule to Merged Main

- .github/workflows/release-notes.yml
- CHANGELOG.md
- Freshli.Cli/Freshli.Cli.csproj
- GitVersion.yml
- Solution for #8  and #7
- Updated reference to Freshli.Lib that was broken after we changed the Nuget Package Name
> (#8) - Add release-notes.yml workflow to github actions and GitVersion.yml to allow automatic versioning

- .github/workflows/ci.yml
Fixes #20.  The fix was to update the CI to not error out if the GitHub milestone had no closed issues.
> Fix issue where build fails if there are no closed issues

- .github/workflows/ci.yml
- GitReleaseManager.yaml
- freshli-cli.sln
Fixes #21.  Fixes the unknown label issue when generating the Github Release and Changelog.  Also added files in the root folder to a VS Solution folder.
> Fix unknown label issue in CI

- README.md
Not much more to say than that. 😄
> Adds CodeClimate badges

- .github/dependabot.yml
Initial setup monitors C# (NuGet), Ruby (Bundler), and GitHub Actions for new versions.
Closes #66.
> Adds dependabot configuration

- .config/dotnet-tools.json
- features/step_definitions/database.rb
- features/version.feature
created a new version.feature file within features folder and added a scenario for freshli --version command
> added version test command

- Corgibytes.Freshli.Cli/CommandOptions/GitCommandOptions.cs
- Corgibytes.Freshli.Cli/CommandRunners/GitCommandRunner.cs
- Corgibytes.Freshli.Cli/Commands/GitCommand.cs
- Corgibytes.Freshli.Cli/Functionality/Cache.cs
- Corgibytes.Freshli.Cli/Functionality/CacheContext.cs
- Corgibytes.Freshli.Cli/Functionality/CachedGitRepo.cs
- Corgibytes.Freshli.Cli/Functionality/Git.cs
- Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
- Corgibytes.Freshli.Cli/Migrations/20220524202324_GitRepository.Designer.cs
- Corgibytes.Freshli.Cli/Migrations/20220524202324_GitRepository.cs
- Corgibytes.Freshli.Cli/Program.cs
- features/git_clone.feature
- features/step_definitions/git.rb
- features/support/commands.rb
- features/support/filesystem.rb
> Git Clone Command (take 2)

- bin/freshli-agent-mock.rb
> Create mock freshli agent in Ruby

- Corgibytes.Freshli.Cli.Test/Commands/MockAgentManager.cs
- Corgibytes.Freshli.Cli.Test/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
- Corgibytes.Freshli.Cli/Functionality/BillOfMaterials/BillOfMaterialsGeneratedEvent.cs
- Corgibytes.Freshli.Cli/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivity.cs
- Corgibytes.Freshli.Cli/Services/AgentReader.cs
- Corgibytes.Freshli.Cli/Services/IAgentReader.cs
- README.md
Fixes #152 
This is not done yet, adding another issue for it as it's depending on this to be merged first: https://github.com/corgibytes/freshli-cli/pull/204/files#diff-8b3691b75312db3758ae2ac096f46f86676c6534002d0cb8832fd462933b4de0
> Bill of materials

- Corgibytes.Freshli.Cli.Test/Functionality/Analysis/ManifestDetectedEventTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivityTest.cs
- Corgibytes.Freshli.Cli/Functionality/Analysis/ManifestDetectedEvent.cs
- Corgibytes.Freshli.Cli/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivity.cs
> ManifestDetectedEvent dispatches GenerateBillOfMaterialsActivity

- Corgibytes.Freshli.Cli/Functionality/Git/GitArchive.cs
Co-authored-by: mscottford <mscottford@users.noreply.github.com>
Co-authored-by: Edwin Kortman <edwin@corgibytes.com>
> Fixes race condition in CreateArchive

- Corgibytes.Freshli.Cli/Commands/AgentsVerifier.cs
Fixes #268
This was the only instance I could find.
> Change DateTimeOffset format to 'o'

- Corgibytes.Freshli.Cli.Test/Functionality/Git/CloneGitRepositoryActivityTest.cs
- Corgibytes.Freshli.Cli/Functionality/Analysis/AnalysisStartedEvent.cs
- Corgibytes.Freshli.Cli/Functionality/Analysis/StartAnalysisActivityBase.cs
- Corgibytes.Freshli.Cli/Functionality/Git/CloneGitRepositoryActivity.cs
This was removed by Edwin's commit and accidentally added back when I merged my branch to main.
This change also removes URL and Branch from GitCloneRepositoryActivity parameters
> Removes git clone repository CLI and test cases

- .github/workflows/ci.yml
Related to this change: https://github.com/corgibytes/freshli-cli/pull/292
> Don't push to NuGet

- Corgibytes.Freshli.Cli.Test/Functionality/Analysis/DetectAgentsForDetectManifestsActivityTest.cs
- Corgibytes.Freshli.Cli/Functionality/Agents/NoAgentsDetectedFailureEvent.cs
- Corgibytes.Freshli.Cli/Functionality/Analysis/DetectAgentsForDetectManifestsActivity.cs
- docs/activities-and-events.md
> No agents detected event

- .codeclimate.yml
- Corgibytes.Freshli.Cli.Test/Functionality/History/ComputeHistoryActivityTest.cs
- Corgibytes.Freshli.Cli/Functionality/Git/ComputeHistory.cs
- Corgibytes.Freshli.Cli/Functionality/Git/InvalidHistoryIntervalException.cs
- Corgibytes.Freshli.Cli/Functionality/History/ComputeHistoryActivity.cs
- docs/activities-and-events.md
> Analyzing repository with an interval bigger than it's age will fail

- Corgibytes.Freshli.Cli.Test/Functionality/FreshliWeb/AnalysisApiCreatedEventTest.cs
- Corgibytes.Freshli.Cli/CommandRunners/AnalyzeRunner.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/AnalysisApiCreatedEvent.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/CreateAnalysisApiActivity.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/ResultsApi.cs
- features/analyze.feature
> Change results url

- Corgibytes.Freshli.Cli.Test/Functionality/Analysis/PrepareCacheForAnalysisActivitySerializationTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/CycloneDxBomReaderTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/FreshliWeb/CreateApiPackageLibYearActivitySerializationTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/FreshliWeb/CreateApiPackageLibYearActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/History/ComputeHistoryActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/LibYear/DeterminePackagesFromBomActivitySerializationTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/LibYear/PackageLibYearCalculatorTest.cs
- Corgibytes.Freshli.Cli.Test/HostedServicesTest.cs
- Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
- Corgibytes.Freshli.Cli/Commands/AgentsVerifier.cs
- Corgibytes.Freshli.Cli/Functionality/CacheDb.cs
- Corgibytes.Freshli.Cli/Functionality/CycloneDxBomReader.cs
- Corgibytes.Freshli.Cli/Functionality/Engine/ApplicationEngine.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/ResultsApi.cs
- Corgibytes.Freshli.Cli/Functionality/Git/GitManager.cs
- Corgibytes.Freshli.Cli/Functionality/History/ComputeHistoryActivity.cs
- Corgibytes.Freshli.Cli/Functionality/Invoke.cs
- Corgibytes.Freshli.Cli/Functionality/JsonCycloneDX.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/DeterminePackagesFromBom.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/LibYearComputedForPackageEvent.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/PackageLibYearCalculator.cs
- Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
- Corgibytes.Freshli.Cli/Migrations/20221017183038_AddCachedPackageLibYears.cs
- Corgibytes.Freshli.Cli/Services/AgentManager.cs
- bin/support/execute.rb
- diagram-generator/Program.cs
> Filter child modules

- Dockerfile
> Adds git to the runtime container

- .codeclimate.yml
- Corgibytes.Freshli.Cli.Test/Functionality/History/ComputeHistoryActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/LibYear/ComputeLibYearForPackageActivityTest.cs
- features/analyze.feature
- features/step_definitions/database.rb
This addresses an oversight on my previous PR where I did not have time to add tests before merging.
> Add tests for cached package lib year

- Corgibytes.Freshli.Cli.Test/CommandRunners/AnalyzeRunnerTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Analysis/PrepareCacheForAnalysisActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Cache/PrepareCacheActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/FreshliWeb/UpdateAnalysisStatusActivitySerializationTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/FreshliWeb/UpdateAnalysisStatusActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
- Corgibytes.Freshli.Cli/CommandOptions/CommandOptions.cs
- Corgibytes.Freshli.Cli/CommandRunners/AgentsCommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/AnalyzeRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/Cache/DestroyCommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/Cache/PrepareCacheRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/CacheCommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/CommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/FailCommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/ICommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/LoadServiceCommandRunner.cs
- Corgibytes.Freshli.Cli/CommandRunners/ScanCommandRunner.cs
- Corgibytes.Freshli.Cli/Commands/RunnableCommand.cs
- Corgibytes.Freshli.Cli/Commands/ScanCommand.cs
- Corgibytes.Freshli.Cli/Functionality/Cache/CachePrepareFailedEvent.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/AnalysisApiStatusUpdatedEvent.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/IResultsApi.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/ResultsApi.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/UpdateAnalysisStatusActivity.cs
- Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
- docs/activities-and-events.md
- features/step_definitions/api.rb
Fixes #235.
Implements `POST /api/v0/analysis-request/{GUID}/{date}` from #235.
> API Implementation Part 2

- Dockerfile
This also required switching from a JRE base image to a JDK base image.
> Adds mvn to production container

- .github/workflows/ci.yml
- .github/workflows/cla.yml
- .github/workflows/generate-diagram.yml
- CHANGELOG.md
- Corgibytes.Freshli.Cli.Test/CommandRunners/AnalyzeRunnerTest.cs
- Corgibytes.Freshli.Cli/Functionality/CommandInvoker.cs
- Corgibytes.Freshli.Cli/Services/AgentReader.cs
- features/analyze.feature
- features/step_definitions/database.rb
> Addresses linter issues

- tools/diagram-generator/diagram-generator.csproj
Consolidates and replaces the following pull requests:
* #410 
* #411 
* #412
> Update diagram generator deps

- .github/workflows/dotnet-tool-checker.yml
- .github/workflows/dotnet-tool-updater.yml
Based on https://github.com/xt0rted/dotnet-tool-update-test.
Fixes #414.
> Adds workflows for keeping `dotnet tool` dependencies up-to-date

- Corgibytes.Freshli.Cli.Test/Extensions/PackageUrlExtensionsTest.cs
- Corgibytes.Freshli.Cli/Extensions/PackageUrlExtensions.cs
- Corgibytes.Freshli.Cli/Services/AgentManager.cs
- Dockerfile
Relates to https://github.com/corgibytes/freshli-agent-dotnet/issues/1
> Issue #1: Include .NET language agent

- Corgibytes.Freshli.Cli.Test/Extensions/PackageUrlExtensionsTest.cs
- Corgibytes.Freshli.Cli.Test/Fixtures/Functionality/LibYear/nuget.NLog-ReleaseHistory.json
- Corgibytes.Freshli.Cli.Test/Functionality/CycloneDxBomReaderTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/LibYear/PackageLibYearCalculatorTest.cs
- Corgibytes.Freshli.Cli.Test/Services/AgentManagerTest.cs
- Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
- Corgibytes.Freshli.Cli.Test/Services/AgentReaderWithJavaAgentTest.cs
- Corgibytes.Freshli.Cli/Extensions/PackageUrlExtensions.cs
- Corgibytes.Freshli.Cli/Functionality/Analysis/DetectAgentsForDetectManifestsActivity.cs
- Corgibytes.Freshli.Cli/Functionality/Analysis/DetectManifestsUsingAgentActivity.cs
- Corgibytes.Freshli.Cli/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivity.cs
- Corgibytes.Freshli.Cli/Functionality/CacheDb.cs
- Corgibytes.Freshli.Cli/Functionality/CacheManager.cs
- Corgibytes.Freshli.Cli/Functionality/CycloneDxBomReader.cs
- Corgibytes.Freshli.Cli/Functionality/FreshliWeb/ResultsApi.cs
- Corgibytes.Freshli.Cli/Functionality/History/CheckoutHistoryActivity.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/ComputeLibYearForPackageActivity.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/DeterminePackagesFromBomActivity.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/IPackageLibYearCalculator.cs
- Corgibytes.Freshli.Cli/Functionality/LibYear/PackageLibYearCalculator.cs
- Corgibytes.Freshli.Cli/Functionality/PackageLibYear.cs
- Corgibytes.Freshli.Cli/Services/AgentManager.cs
- Corgibytes.Freshli.Cli/Services/AgentReader.cs
- Dockerfile
These changes continue the work of integrating the newly created [.NET](https://github.com/corgibytes/freshli-agent-dotnet) language agent. 
Resolves https://github.com/corgibytes/freshli-agent-dotnet/issues/1
> Agent.NET-Issue 1: Integrate .NET language agent

- CONTRIBUTORS.md
There are a bunch of people who have helped out on this project. Not everyone has made direct commits. This file is a place to be able to track of everyone.
> Adds contributors file

- Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
> Switches to Corgibytes fork of Spectre.Console

- Corgibytes.Freshli.Cli.Test/Functionality/Api/AnalysisApiCreatedEventTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/ApiHistoryStopCreatedEventTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/ApiPackageLibYearCreatedEventTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/Auth/SnakeCaseStringsTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/CreateAnalysisApiActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/CreateApiHistoryStopActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/CreateApiPackageLibYearActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Api/UpdateAnalysisStatusActivityTest.cs
- Corgibytes.Freshli.Cli.Test/Functionality/Support/ConfigurationTest.cs
- Corgibytes.Freshli.Cli/Commands/Auth/AuthCommand.cs
- Corgibytes.Freshli.Cli/Commands/Auth/AuthCommandRunner.cs
- Corgibytes.Freshli.Cli/Commands/MainCommand.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/ApiCredentials.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/AuthClient.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/AuthException.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/ConvertToAuthDevice.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/ConvertToFreshliApiCredentials.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/DeviceAuthToken.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/IAuthClient.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/OAuthDeviceCodeResponse.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/OAuthTokenResponse.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/SnakeCaseNamingPolicy.cs
- Corgibytes.Freshli.Cli/Functionality/Api/Auth/SnakeCaseStrings.cs
- Corgibytes.Freshli.Cli/Functionality/Api/ResultsApi.cs
- Corgibytes.Freshli.Cli/Functionality/Cache/CacheManager.cs
- Corgibytes.Freshli.Cli/Functionality/Cache/ICacheManager.cs
- Corgibytes.Freshli.Cli/Functionality/Support/Configuration.cs
- Corgibytes.Freshli.Cli/Functionality/Support/IConfiguration.cs
- Corgibytes.Freshli.Cli/ServiceBuilder.cs
> Implements `auth` command
