corgibytes/freshli-cli

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/azcli-debian.sh
.gitignore
.vscode/launch.json
.vscode/tasks.json

Allows for Visual Studio Code's Dev Containers to be used, and sets the path to allow for development using a Docker image.
The Dev Container created will also install the following plugins to assist with testing:
* .NET Test Explorer
* Coverage Gutters

Adds VSCode Dev Container support

---

.github/workflows/cla.yml

Fixes #35.
By default the CLA build process triggers on [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) which means it will use the old CLA workflow in `release-0.4` branch which has not been fixed and will still raise an error.  To test the updated CLA file I temporarily changed the workflow to trigger on [pull_request](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request).  You can see the results of my tests [here](https://github.com/corgibytes/freshli-cli/runs/3069204651?check_suite_focus=true).

Fix a warning in the CLA build process.

---

README.md

Updated the ReadMe to make it more user friendly and include the recent changes to the CLI such as:
- Downloading OS specific versions of the CLI.
- Install Freshli as a .NET Tool.
- The data returned when running Freshli.
- Dependency managers supported by Freshli.
- Support for multiple languages such as Spanish.
Fixes #22.

Updated the release notes for v0.4.0 release

---

.github/workflows/ci.yml

This PR removes the warning from #33 from the .NET Core CI process, basically converting from using the provided action to calling the `git-releasemanager` command directly.
This PR took some work, as upgrading to later versions of the GitReleaseManager tool proves to have some issues, and depending how deep we'd like to take this, may warrant opening issues with the tool on their repository.
The following draft PR shows the work process that occurs with different configurations, which yields the following:
* If we upgrade to GitReleaseManager 0.12, it still requires tagName via [this documentation](https://gittools.github.io/GitReleaseManager/docs/commands/add-assets) and if tagName is provided, we'll receive a ObjectReferenceError that I believe relates to how the assets are passed in: …

Fixes #33, removes warning for GitReleaseManager on Add Asset

---

Corgibytes.Freshli.Cli.Test/OutputFormatterTest.cs
Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
Corgibytes.Freshli.Cli/OutputFormatter.cs
README.md
global.json

Upgrade the CLI to Freshli-Lib v0.4.0 which supports multiple manifest files.
Didn't bother adding a bunch of new tests as these existing test files are deleted/moved in `main`.  I'll have to deal with merge conflicts and possibly add more tests when merging the `release-0.4` branch to `main.

Upgrade to Freshli-Lib v0.4.0

---

.github/workflows/ci.yml

It's possible that the command syntax changed, and that `-n true` used to be a valid choice. Now however, it looks like just `-n` or `--no-symbols` is the correct way to specify this option.

Corrects syntax of no symbols option on nuget publish

---

Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
features/cache.feature
features/help.feature

Renames the binary that's produced when the project is built.
Closes #65.

Rename executable from `Corgibytes.Freshli.Cli` to `freshli`

---

.github/workflows/ci.yml

GitReleaseManager now works with .NET 6, so we don't need to install this older version anymore. This should silence a warning that we're getting in the build output about .NET 3.0 not having support anymore.
Closes #72.

Removes installation of .NET Core 3

---

Corgibytes.Freshli.Cli.Test/Corgibytes.Freshli.Cli.Test.csproj
Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj

The dependabot created pull requests to update these dependencies didn't work because one of the libraries depends on the other. I suspect this might be an issue again the next time these need to be upgraded.
Replaces #89.
Replaces #90.

Bumps System.CommandLine dependencies to latest versions

---

README.md

This PR originates from some struggles I had with setting up the environment. I saw the devcontainer environment, but I figured both methods described would work fine. Alas! I had some trouble setting up the first, so I spent longer than I wanted. To not have the next person make the same mistake as I did, I added some text to the README to clarify that the preferred way of setting up the development environment is the devcontainer. Also, if they run into the same error, how to solve it.

Clarify what the preferred way of setting up the development environment is

---

.codeclimate.yml

We've upped the threshold for this check a few times. Each time it was
for boiler plate code in tests. The check itself is useful but only if
we could exclude the tests for this particular check which we can't
(yet?). Until that time, since it's losing value, disable the check
entirely.
https://docs.codeclimate.com/docs/advanced-configuration#exclude-patterns
> Exclusions can only be made at the global level (excluding code from all analysis) or at the plugin-level (excluding code only from specific third-party plugins). Currently, exclusions cannot be made for individual maintainability checks.

Disable the similar code check in CodeClimate

---

Corgibytes.Freshli.Cli/Functionality/Git/GitSource.cs
Corgibytes.Freshli.Cli/Functionality/Invoke.cs

Adds the Invoke.Command() and Invoke.Freshli() methods for
executing external processes with CliWrap. This eliminates
boilerplate from the rest of the project.
Changes all prior direct invocations of processes with CliWrap
to use Invoke.Command() instead.
Invoke.Freshli() method will be needed in upcoming work. This just
defines it, since it was written as part of a now-abandoned task
and worth retaining.
---
I credited Dona on this task because she helped write the method
that I further developed here into Invoke.Freshli() and Invoke.Command().

Abstract External Process Calls

---

.github/workflows/cla.yml

The v2.0.0 release seems to have gone away. We're now getting errors that the version can't be found.

build: switch CLA assistant to version 2.1.3-beta

---

Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj

Fixes #123 
https://stackoverflow.com/questions/12729922/how-to-set-cultureinfo-invariantculture-default
https://docs.microsoft.com/EN-US/dotnet/core/runtime-config/globalization
There are a few ways that invariant culture can be set as default yet, from what I could find, none of those were being used.

Explicitly set the culture to the invariant culture

---

Corgibytes.Freshli.Cli.Test/Functionality/Git/CloneGitRepositoryActivityTest.cs
Corgibytes.Freshli.Cli/CommandRunners/Git/GitCloneCommandRunner.cs
Corgibytes.Freshli.Cli/Functionality/Git/CachedGitSourceRepository.cs
Corgibytes.Freshli.Cli/Functionality/Git/CloneGitRepositoryActivity.cs
Corgibytes.Freshli.Cli/Functionality/Git/CloneGitRepositoryFailedEvent.cs
Corgibytes.Freshli.Cli/Functionality/Git/GitRepositoryClonedEvent.cs

Fixes #148 
This change ports the git clone repository command runner to invoke git clone repository using the new CQRS architecture.

Port git clone functionality to CQRS-lite architecture

---

Corgibytes.Freshli.Cli.Test/Functionality/Analysis/CacheWasNotPreparedEventTest.cs
Corgibytes.Freshli.Cli.Test/ProgramTest.cs
Corgibytes.Freshli.Cli/CommandRunners/LoadServiceCommandRunner.cs
Corgibytes.Freshli.Cli/Commands/LoadServiceCommand.cs
Corgibytes.Freshli.Cli/Commands/MainCommand.cs
Corgibytes.Freshli.Cli/Functionality/Analysis/CacheWasNotPreparedEvent.cs
Corgibytes.Freshli.Cli/Functionality/Engine/ApplicationEngine.cs
Corgibytes.Freshli.Cli/Functionality/Engine/IApplicationActivityEngine.cs
Corgibytes.Freshli.Cli/Functionality/Engine/IApplicationEventEngine.cs
Corgibytes.Freshli.Cli/Functionality/LoadServiceProviderActivity.cs
Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs

I've tested a few things before ending up on this solution. 
What I started with was @mscottford suggestion to use the `JsonContractResolver`:
```csharp
...
else if (objectType == typeof(IServiceProvider))
{
var serviceProvider = _serviceScopeFactory.CreateScope().ServiceProvider;
if (serviceProvider != null)
{
baseContract.DefaultCreator = () => serviceProvider;
}
}
...
```
This results in a self referencing loop, though. Potential solutions online for this problem are either: ignore it, ignore it globally or remove it. Ignoring it with `[JsonIgnore]` does make the loop error go away, but it also ignores the contract resolver.
Examples:
https://makolyte.com/newtonsoft-json-jsonserializationexception-self-referencing-loop-detected-for-property/
```csharp
public interface …
```

Service provider always null when used in Activities

---

Corgibytes.Freshli.Cli/Functionality/Analysis/AnalysisLocation.cs
Corgibytes.Freshli.Cli/Functionality/Analysis/IAnalysisLocation.cs

In several places we've been wanting to re-use this object for more then just the Path. It's been our identifier for the analysis. Instead of passing cache directory, repository, and optionally commit identifier to each thing the entire time. Just pass the AnalysisLocation

Make the fields of AnalysisLocation public

---

.github/release-drafter.yml

Related to https://github.com/corgibytes/freshli-cli/pull/277
Release drafter needs a template file in the main branch to work.

Adds a template for the release drafter

---

Corgibytes.Freshli.Cli.Test/Functionality/History/ComputeHistoryActivityTest.cs
Corgibytes.Freshli.Cli/Functionality/History/CheckoutHistoryActivity.cs
Corgibytes.Freshli.Cli/Functionality/History/ComputeHistoryActivity.cs
Corgibytes.Freshli.Cli/Functionality/History/HistoryIntervalStopFoundEvent.cs
Corgibytes.Freshli.Cli/Functionality/History/HistoryStopCheckedOutEvent.cs

Fixes deserialization of CheckoutHistoryActivity - because analysisLocation was being used to initialize _cacheDirectory, _repositoryId, and _commitId, but was not saved in the object, the values were not being deserialized correctly when the activity ran.  This change saves _analysisLocation in the object instead and uses _analysisLocation directly in Handle.  This change also passes _analysisLocation to HistoryStopCheckedOutEvent instead of creating a new AnalysisLocation instance.
Fixes HistoryIntervalStopFoundEvent which was expecting the Git commit Id to be provided in AnalysisLocation and was not using the GitCommitIdentifier field. This change also creates a new historyStopLocation and passes that to the event instead of overwriting the values in the same AnalysisLocation which …

Fixes for compute history and checkout history activities

---

Corgibytes.Freshli.Cli.Test/Functionality/Analysis/AgentDetectedForDetectManifestEventTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/Analysis/DetectAgentsForDetectManifestsActivityTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/Analysis/DetectManifestsUsingAgentActivityTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/Analysis/ManifestDetectedEventTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivityTest.cs
Corgibytes.Freshli.Cli/Functionality/Analysis/AgentDetectedForDetectManifestEvent.cs
Corgibytes.Freshli.Cli/Functionality/Analysis/DetectAgentsForDetectManifestsActivity.cs
Corgibytes.Freshli.Cli/Functionality/Analysis/DetectManifestsUsingAgentActivity.cs
Corgibytes.Freshli.Cli/Functionality/Analysis/ManifestDetectedEvent.cs
Corgibytes.Freshli.Cli/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivity.cs
Corgibytes.Freshli.Cli/Functionality/History/HistoryStopCheckedOutEvent.cs

This changes the chain of activities in the analyze command to pass the agentExecutablePath instead of serializing/deserializing the IAgentReader object.

Gets AgentReader from IAgentManager via the eventClient.ServiceProvider

---

Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
Corgibytes.Freshli.Cli/Services/AgentReader.cs

Ensures that the list of manifest files is empty, as expected when no manifest files are found by the agent.

Returns and empty list of detect-manifests returns an empty string

---

Corgibytes.Freshli.Cli.Test/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivityTest.cs
Corgibytes.Freshli.Cli/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivity.cs
Corgibytes.Freshli.Cli/Services/AgentReader.cs

Found two small bugs. One is that I forgot a DateTime format, the other one was that the working directory wasn't passed so we were asking the agent to run this:
```shell
/usr/local/bin/freshli-agent-java process-manifest pom.xml 2022-09-23T13:37:24Z
```
Which doesn't work because it can't locate `pom.xml`

Agent bugs

---

Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
Corgibytes.Freshli.Cli/Functionality/Configuration.cs

For the configuration object to be deserialized correctly in AnalysisLocation there needs to be a constructor that will set GitPath and CacheDir from the serialized data.  Because environment is not saved in the class it cannot be used to deserialize the object.

Fixes deserialization of Configuration class in Newtonsoft.json

---

Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj

This PR combines these PRs:
https://github.com/corgibytes/freshli-cli/pull/335
https://github.com/corgibytes/freshli-cli/pull/333
https://github.com/corgibytes/freshli-cli/pull/331
https://github.com/corgibytes/freshli-cli/pull/330
Some of them need to be upgraded together otherwise we'll get this error:
```
/home/runner/work/freshli-cli/freshli-cli/Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj : error NU1605: Detected package downgrade: Microsoft.Extensions.Hosting.Abstractions from 7.0.0-rc.2.22472.3 to 7.0.0-rc.1.22426.10. Reference the package directly from the project to select a different version.  [/home/runner/work/freshli-cli/freshli-cli/freshli-cli.sln]
```

Upgrade Microsoft extensions together

---

Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs

This fixes a failure on the `main` branch when running `dotnet test`.

Fixes expected path in failing .NET test

---

Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj

This PR updates both NLog extensions at the same time. A replacement for these two PRs:
https://github.com/corgibytes/freshli-cli/pull/374
https://github.com/corgibytes/freshli-cli/pull/375

Update NLog extensions to latest version

---

Corgibytes.Freshli.Cli.Test/Functionality/Analysis/PrepareCacheForAnalysisActivityTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/Cache/PrepareCacheActivityTest.cs
Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
Corgibytes.Freshli.Cli/Functionality/Cache/CachePrepareFailedEvent.cs
Corgibytes.Freshli.Cli/Functionality/CacheDb.cs
Corgibytes.Freshli.Cli/Functionality/Git/CachedGitSourceId.cs
Corgibytes.Freshli.Cli/Functionality/Git/CachedGitSourceRepository.cs
Corgibytes.Freshli.Cli/Functionality/Git/GitArchive.cs
Corgibytes.Freshli.Cli/Functionality/Git/ICachedGitSourceRepository.cs
Corgibytes.Freshli.Cli/Functionality/ICache.cs
Corgibytes.Freshli.Cli/Functionality/ICacheManager.cs

Database retry mechanism

---

Corgibytes.Freshli.Cli/Commands/AgentsVerifier.cs
features/agents_verify.feature

Related to #359 
There were a few problems with the AgentsVerifier that caused it not to run at all. I also took the opportunity to do a bit of refactoring:
- Use one loop for running DetectManifests
- Pass the targetDirectory, as we need an absolute URL for the agent. This was a repository URL before.
- The check for validating detected manifests versus processed manifests was always reporting false because the processed manifests in the loop is always 1
- Detect manifests only ran for Gemfiles

Fix failing agents verify test

---

features/analyze.feature

Fixes #359
@mscottford I think this fix, and the fix introduced here https://github.com/corgibytes/freshli-cli/pull/372
Are cases where the suite is actually failing. If I run the tests locally, separately, they don't fail. If I run them all at once the first two of analyze.feature fail. Separating the realistic scenario into a different file only causes that one to fail. 
So I think for fixing the CI on the main branch we have to look at what you suggested in Slack to get GitHub actions running on a bigger computer.

Fix failing analyze feature tests

---

.codeclimate.yml
Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
Corgibytes.Freshli.Cli/Functionality/CommandInvoker.cs
Corgibytes.Freshli.Cli/Functionality/ICommandInvoker.cs
Corgibytes.Freshli.Cli/Services/AgentReader.cs

* Adds ability to retry with an exponential delay to the `CommandInvoker` class
* Makes some improvements to the log output when a command fails.
* Sets the max number of retries for `retrieve-release-history` to 3
Fixes #391.

Retries calls to `retrieve-release-history`

---

.github/workflows/ci.yml

When dependabot initiates a build, GitHub Actions prevents it from accessing any secrets. The action that publishes the results needs access to a value that's stored in the secrets, but the action fails because the value is just blank. This change disables the attempt to send the data when a build in initiated by dependabot.

Prevent dependabot builds from attempting to publish coverage data

---

.github/workflows/ci.yml
Corgibytes.Freshli.Cli.Test/Functionality/AgentsDetectorTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/EnvironmentTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/ExecutableFinderTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/MockEnvironment.cs
Corgibytes.Freshli.Cli/Commands/AgentsDetector.cs
Corgibytes.Freshli.Cli/Functionality/Environment.cs
Corgibytes.Freshli.Cli/Functionality/ExecutableFinder.cs
Corgibytes.Freshli.Cli/Functionality/IEnvironment.cs
Corgibytes.Freshli.Cli/Functionality/IExecutableFinder.cs
Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
features/agents.feature
features/step_definitions/filesystem.rb

- On Windows uses PATHEXT environment variable to find executable files
- On Mac/Linux uses the executable bit to determine if a file is an executable
- Changes AgentDetector to use the new ExecutableFinder
Fixes #422.

Adds ExecutableFinder

---

Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj

- Upgrade NLog.Extensions.Hosting from 5.1.0 to 5.2.0
- Upgrade NLog.Extensions.Logging from 5.1.0 to 5.2.0
Replaces:
- #429 
- #428

Upgrade NLog.Extensions.* from 5.1.0 to 5.2.0

---

.editorconfig
.github/workflows/ci.yml
.github/workflows/cla.yml
.github/workflows/generate-diagram.yml
bin/format.rb
bin/lint.rb
bin/support/execute.rb
bin/test.rb
features/support/aruba.rb
features/support/filesystem.rb
features/support/hooks/cleanup.rb
global.json

This includes a `windows_safe_recursive_delete` method that works around some quirks that crop up when deleting some of the git clones that can appear in the Aruba home directory.
The contents of the `.git` directory are marked as read-only, and that causes problems on Windows by default.
Also, on Windows, if the full path to a file becomes longer than around 260 characters, then `File.stat` will report that the file does not exist. This can be worked around, by prefixing the full path with `\\?\`, thus putting the path in UNC format. See https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats for more information on the UNC path format.
While working on this I also discovered that linting wasn't running as part of the Windows builds. The `bin/lint.rb` file wasn't being run …

Ensures that the aruba home directory is removed

---

.editorconfig
.github/workflows/ci.yml
Corgibytes.Freshli.Cli.Test/Functionality/Analysis/DetectManifestsUsingAgentActivityTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/BillOfMaterials/GenerateBillOfMaterialsActivityTest.cs
Corgibytes.Freshli.Cli.Test/Functionality/LibYear/ComputeLibYearForPackageActivityTest.cs
Corgibytes.Freshli.Cli.Test/Helpers/CallHelpers.cs
Corgibytes.Freshli.Cli.Test/Services/AgentManagerTest.cs
Corgibytes.Freshli.Cli.Test/Services/AgentReaderTest.cs
Corgibytes.Freshli.Cli.Test/Services/AgentReaderWithJavaAgentTest.cs
Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj
Corgibytes.Freshli.Cli/Functionality/CacheDb.cs
Corgibytes.Freshli.Cli/Functionality/Configuration.cs
Corgibytes.Freshli.Cli/Functionality/FreshliWeb/ResultsApi.cs
Corgibytes.Freshli.Cli/Functionality/IConfiguration.cs
Corgibytes.Freshli.Cli/IoC/FreshliServiceBuilder.cs
Corgibytes.Freshli.Cli/Program.cs
Corgibytes.Freshli.Cli/Services/AgentManager.cs
Corgibytes.Freshli.Cli/Services/AgentReader.cs
Corgibytes.Freshli.Cli/Services/AgentRetrievalFailure.cs
Corgibytes.Freshli.Cli/Services/IAgentManager.cs
Corgibytes.Freshli.Cli/Services/IAgentReader.cs
Corgibytes.Freshli.Cli/Services/PortFinder.cs
Corgibytes.Freshli.Cli/proto/freshli_agent.proto
features/step_definitions/api.rb

This is an attempt to make performance improvements as part of #356.
* Starts up to 5 agent processes with the `start-service` command to run the gRPC service, and hands out `AgentReader` instances that communicate with those servers in a round-robin fashion.
* Adds retry logic to Freshli Web API calls, and also changes to a shared `HttpClient` instance. The retry logic should improve reliability, and the shared `HttpClient` instance should improve performance.
* Improves reliability of cache database reads by using retries when reading from the cache database.

Uses gRPC service for communicating with the Freshli agents

---

Corgibytes.Freshli.Cli/Corgibytes.Freshli.Cli.csproj

Upgrades all gRPC and Protobuf dependencies to their latest versions.
* Replaces #478 
* Replaces #477 
* Replaces #476 
* Replaces #475 
* Replaces #474

Upgrades gRPC dependencies

---

.github/workflows/ci.yml
Dockerfile

* Makes adjustments to how docker container image is built
* Makes sure that CI only attempts to build the docker container if all of the tests pass
* Makes sure that CI runs some smoke tests against the docker container before publishing the built image
Addresses the following issues:
* Fixes #612 
* Fixes #605

DotNet in docker container
